### ISSUE TITLE
[Bug Report] Commands `/avatar` causing module crash

### ISSUE THREAD

**Issue by Rewtio** [Clytage/whatsapp-bot#275]
Log: 
```
const isDataURL = (s) => !!s.match(/^data:((?:\w+\/(?:(?!;).)+)?)((?:;[\w\W]*?[^;])*),(.+)$/g);
                             ^

TypeError: Cannot read properties of undefined (reading 'match')
    at isDataURL (D:\Data\WebProjects\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\utils\tools.js:133:30)
    at Client.<anonymous> (D:\Data\WebProjects\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:1572:40)
    at Generator.next (<anonymous>)
    at D:\Data\WebProjects\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Data\WebProjects\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:23:12)
    at Client.sendImage (D:\Data\WebProjects\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:1570:16)
    at AvatarCommand.execute (file:///D:/Data/WebProjects/whatsapp-bot/dist/commands/general/AvatarCommand.js:18:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/Data/WebProjects/whatsapp-bot/dist/structures/WhatsappBot.js:18:17
```

**Comment by noxzym** [comment]
invalid issue since we migrate to baileys and removed that command
